# Generated by Django 5.2 on 2026-04-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('fid', models.IntegerField()),
                ('realname', models.CharField(max_length=11)),
                ('content', models.TextField()),
                ('ctime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=70)),
                ('foodtype', models.CharField(max_length=20)),
                ('recommend', models.CharField(blank=True, max_length=255, null=True)),
                ('imgurl', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'myapp_foods',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
            ],
            options={
                'unique_together': {('user', 'food')},
            },
        ),
    ]
