# Generated by Django 5.2 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='realname',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['fid'], name='foods_comme_fid_bd4565_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['uid'], name='foods_comme_uid_510aaf_idx'),
        ),
    ]
