# Generated by Django 5.2 on 2026-04-10

from django.db import migrations, models


def backfill_food_counts(apps, schema_editor):
    foods_model = apps.get_model("foods", "Foods")
    collect_model = apps.get_model("foods", "Collect")
    comment_model = apps.get_model("foods", "Comment")

    for food in foods_model.objects.all().only("id"):
        collect_count = collect_model.objects.filter(food_id=food.id).count()
        comment_count = comment_model.objects.filter(fid=food.id).count()
        foods_model.objects.filter(id=food.id).update(
            collect_count=collect_count,
            comment_count=comment_count,
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_comment_realname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='collect_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='foods',
            name='comment_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_food_counts, noop_reverse),
    ]
