# Generated by Django 5.2 on 2026-04-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_external_user_id_user_source_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('categories', models.TextField(blank=True, default='')),
                ('stars', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('aggregated_review_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'yelp_business',
                'ordering': ['-review_count', '-stars', 'name'],
                'indexes': [models.Index(fields=['state', 'city'], name='yelp_busine_state_145d2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='YelpReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=32, unique=True)),
                ('stars', models.FloatField(default=0.0)),
                ('text', models.TextField(blank=True, default='')),
                ('review_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recommendations.yelpbusiness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yelp_reviews', to='users.user')),
            ],
            options={
                'db_table': 'yelp_review',
                'ordering': ['-review_date', '-id'],
                'indexes': [models.Index(fields=['business', 'review_date'], name='yelp_review_busines_65d1b0_idx'), models.Index(fields=['user', 'review_date'], name='yelp_review_user_id_9e4ece_idx')],
            },
        ),
    ]
