# Generated by Django 5.2 on 2026-04-08 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('info', models.TextField(blank=True, max_length=255, null=True)),
                ('face', models.CharField(blank=True, max_length=255, null=True)),
                ('regtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
