# Generated by Django 6.0.3 on 2026-03-25 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=70)),
                ('foodtype', models.CharField(max_length=20)),
                ('recommand', models.CharField(max_length=255, null=True)),
                ('imgurl', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('info', models.TextField(max_length=255, null=True)),
                ('face', models.CharField(blank=True, max_length=255, null=True)),
                ('regtime', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
